---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sbringbootdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: springbootapp
 template:
  metadata:
   name: springbootapppod
   labels:
     app: springbootapp	 
  spec: 
    containers:
    - name: springbootappcontainer
      image: hunjan/springboot
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: springbootsvc
spec:
  type: LoadBalancer
  selector:
   app: springbootapp
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 31439
...
